services:
    oai-du:
        image: oaisoftwarealliance/oai-gnb:develop
        privileged: true
        container_name: oai-du
        environment:
            ASAN_OPTIONS: detect_leaks=0
        networks:
            oai-net:
                ipv4_address: 10.1.100.10
        volumes:
            - ./config/ran/gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        entrypoint: >
            /tini -v -- /opt/oai-gnb/bin/entrypoint.sh /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf
            --sa --telnetsrv --rfsim --log_config.global_log_options level,nocolor,time

    oai-nr-ue-slice1:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: oai-nr-ue-slice1
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3619200000
                                    --uicc0.imsi 001010000000001
                                    --uicc0.dnn oai1
                                    --uicc0.nssai_sst 1
                                    --uicc0.nssai_sd 1
                                    --rfsimulator.serveraddr 10.1.100.10
        networks:
            oai-net:
                ipv4_address: 10.1.100.101
        volumes:
            - ./config/ran/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        entrypoint: >
            /tini -v -- /opt/oai-nr-ue/bin/entrypoint.sh /opt/oai-nr-ue/bin/nr-uesoftmodem -O /opt/oai-nr-ue/etc/nr-ue.conf

    oai-nr-ue-slice2:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: oai-nr-ue-slice2
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3619200000
                                    --uicc0.imsi 001010000000002
                                    --uicc0.dnn oai2
                                    --uicc0.nssai_sst 1
                                    --uicc0.nssai_sd 2
                                    --rfsimulator.serveraddr 10.1.100.10
        networks:
            oai-net:
                ipv4_address: 10.1.100.102
        volumes:
            - ./config/ran/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        entrypoint: >
            /tini -v -- /opt/oai-nr-ue/bin/entrypoint.sh /opt/oai-nr-ue/bin/nr-uesoftmodem -O /opt/oai-nr-ue/etc/nr-ue.conf

networks:
    oai-net:
        external: true
