services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        networks:
            oai-net:
                ipv4_address: 10.1.20.1
        privileged: true

    oai-nrf-slice:
        container_name: "oai-nrf-slice"
        image: oaisoftwarealliance/oai-nrf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./config/cn/slice1.yaml:/openair-nrf/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.2
        privileged: true

    oai-udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./config/cn/slicing_base.yaml:/openair-udr/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.3
        privileged: true

    oai-udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./config/cn/slicing_base.yaml:/openair-udm/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.4
        privileged: true

    oai-ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./config/cn/slicing_base.yaml:/openair-ausf/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.5
        privileged: true
    
    oai-nssf:
        container_name: "oai-nssf"
        image: oaisoftwarealliance/oai-nssf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./config/cn/slicing_base.yaml:/openair-nssf/etc/config.yaml
            - ./config/cn/nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            oai-net:
                ipv4_address: 10.1.20.6

    oai-amf:
        container_name: "oai-amf"
        image: oai-amf-hardcoded-configured-slice:latest
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./config/cn/slicing_base.yaml:/openair-amf/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.7
        privileged: true

    oai-smf-slice1:
        container_name: "oai-smf-slice1"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./config/cn/slice1.yaml:/openair-smf/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.81
        privileged: true
    
    oai-smf-slice2:
        container_name: "oai-smf-slice2"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./config/cn/slice2.yaml:/openair-smf/etc/config.yaml
        networks:
            oai-net:
                ipv4_address: 10.1.20.82
        privileged: true

    oai-upf-slice1:
        container_name: "oai-upf-slice1"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./config/cn/slice1.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            oai-net:
                ipv4_address: 10.1.20.91
            oai-n6:
        entrypoint: "/openair-upf/bin/oai_upf -c /openair-upf/etc/config.yaml -o"

    oai-upf-slice2:
        container_name: "oai-upf-slice2"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./config/cn/slice2.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            oai-net:
                ipv4_address: 10.1.20.92
            oai-n6:
        entrypoint: "/openair-upf/bin/oai_upf -c /openair-upf/etc/config.yaml -o"

networks:
    oai-net:
        external: true
    oai-n6:
        driver: bridge
        name: oai-n6
        ipam:
            config:
                - subnet: 172.50.0.0/24
                  gateway: 172.50.0.1
        driver_opts:
            com.docker.network.bridge.name: "oai-n6"
